### ISSUE TITLE
Raspberry Pi 3B on Debian

### ISSUE THREAD

**Issue by jimlynnjulian** [kevinchiu/sunpath#1]
Hello,

The 'color.h' file is not part of the resident gcc compiler in Raspbian/Debian.
When 'color.h' is commented out, undeclared variables sunefficacy and skyefficacy cause a failure.
The variables are used without declaration.

**Comment by kevinchiu** [comment]
Interesting. I'm actually not great at C - would you be able to provide a pull request to fix this?

**Comment by jimlynnjulian** [comment]
Hello,

   Thank you for your response.
   Not being great at C myself, I submitted the query to an online C/C++ programming group.
   One of the members directed me to the Radiance repository and supplied three or four lines to build Radiance on Raspberry Pi.
   This is the line of pursuit I'm following now. If I find compilation of gensky requires but a few extra files, I'll get involved.

Cogito ergo sum. - René DesCarte ~1665
("I think, therefore I am")
Sum ergo cogito. - Google ~2014
("So I'm thinking...")
